### ISSUE TITLE
Feature request: Description for bars

### ISSUE THREAD

**Issue by alanmcg** [isaozler/pareto-chart#14]
Excellent graph, looks really nice and works well. I think it could be improved by having the message printed under each bar, as in this example:
![image](https://user-images.githubusercontent.com/43033315/101148449-ecd0f200-361d-11eb-91fe-35a92092a5d7.png)

The requirement to mouseover the bar to see the description makes it kind of useless for non interactive displays such as a monitoring wall (kiosk mode).

**Comment by isaozlerfm** [comment]
Hi @alanmcg thx! Glad it works for you. This would indeed be a good improvement 👍

**Comment by OcelotZero** [comment]
Isa, I would like to make the same request. Having the metric name under each bar would be a huge improvement.

**Comment by smnoel22** [comment]
@isaozlerfm Indeed this would make more sense. Any chance we can have the labels show where they would normally appear on a pareto chart vs hovering?

**Comment by isaozlerfm** [comment]
Hi guys, been a while, but this feature is implemented in the latest version 👍
