### ISSUE TITLE
Pop-up with detail description message is not working for Grafana v9+

### ISSUE THREAD

**Issue by LincolnG4** [isaozler/pareto-chart#17]
Hello, 

First, congratulations for your really great job! 
Since I move from Grafana 7.1.5 to Grafana 9.1.3 I can't see anymore the pop-up with detail description message

this pop-up is not showing up anymore: 
![image](https://user-images.githubusercontent.com/59087790/189104201-260e5879-8c21-4eab-b03e-1ddaf01589d8.png)

Is it possible to be implemented ?

**Comment by isaozler** [comment]
Hi @LincolnG4

Thanks for your feedback! Will definitely check it out to make it compatible with 9+

**Comment by isaozler** [comment]
Hi @LincolnG4 with the latest release (still in the review progress) this issue should be fixed.

Will update this ticket once it is released.

You can already test v0.3.3 locally
https://github.com/isaozler/pareto-chart/releases/download/v0.3.3/isaozler-paretochart-panel-0.3.3.zip

**Comment by isaozler** [comment]
@LincolnG4 the plugin is released, fyi

can you verify if your issue is resolved?

**Comment by LincolnG4** [comment]
I just tested here and looks everything is working fine !! Thanks a lot !
