### ISSUE TITLE
Tooltip component position

### ISSUE THREAD

**Issue by FiloCara** [isaozler/pareto-chart#18]
Hello,

First of all, thank you for developing this great panel.

I have recently updated the plugin to the last version (0.3.3) from version 0.3.2.
Since then the tooltip component always appears in the top right corner regardless of the position of the panel in the dashboard.

<img src="https://user-images.githubusercontent.com/47248016/194400512-56be46e3-c83a-4f4c-a6de-1a2a7c4dd31b.png" width="600">

I'm using Grafana 7.15.

I'm not a CSS expert, but the issue seems related to the _fixed_ position of the _tooltip__container_ div. Why not using an _absolute_ position instead? 

Thank you

**Comment by isaozler** [comment]
Hi @FiloCara 

Thanks! Great it helps you out.

Indeed that was a left over from version 0.3.2, I've updated and submitted the updated to Grafana,

With 0.3.4 it should be fixed

**Comment by isaozler** [comment]
It's published btw @FiloCara, can you please confirm if this resolves your issue?

**Comment by FiloCara** [comment]
Yes, it is working perfectly.
Thank you
